Braniac/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include('django.conf.urls.i18n')),
    path("", include("mainapp.urls", namespace='mainapp')),
    path("authapp/", include("authapp.urls", namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))  # Подключение debug toolbar'a
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавления MEDIA_URL'a

authapp/urls.py
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView
from authapp.apps import AuthappConfig
from django.urls import path

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/<int:pk>', EditView.as_view(), name='edit'),
]

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("login/", views.LoginPageView.as_view(), name="login"),

    # Courses
    path("courses/", cache_page(300)(views.CoursesListView.as_view()), name="courses"),
    path("courses/<int:pk>/", views.CoursesDetailView.as_view(), name="courses_detail", ),
    path("courses/feedback/", views.CourseFeedbackCreateView.as_view(), name="course_feedback", ),

    # News
    path("news/", views.NewsPageView.as_view(), name="news"),
    path("news/add/", views.NewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/update/", views.NewsUpdateView.as_view(), name="news_update"),
    path("news/<int:pk>/delete/", views.NewsDeleteView.as_view(), name="news_delete"),
    path("news/<int:pk>/detail/", views.NewsDetailView.as_view(), name="news_detail"),

    # Logs
    path("logs/", views.LogView.as_view(), name="log_list"),
    path("logs/download/", views.LogDownloadView.as_view(), name="log_download"),

]

mainapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

NULLABLE = {'blank': True, 'null': True}


class MyCustomManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class BaseModel(models.Model):
    # objects = MyCustomManager()
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("created"), editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name=_("updated"), editable=False)

    deleted = models.BooleanField(default=False, verbose_name=_('deleted'))

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        abstract = True


class News(BaseModel):
    title = models.CharField(max_length=128, verbose_name=_('header'))
    preambule = models.CharField(max_length=1024, verbose_name=_('short description'))

    body = models.TextField(**NULLABLE, verbose_name=_('body'))
    body_as_markdown = models.BooleanField(
        default=False, verbose_name=_('As markdown')
    )

    def __str__(self):
        return f'{self.pk} {self.title}'

    class Meta:
        verbose_name = _('News')
        verbose_name_plural = _('News')


class Courses(BaseModel):
    name = models.CharField(max_length=256, verbose_name=_("name"))

    description = models.TextField(verbose_name=_("Description"), blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name=_("As markdown"), default=False)

    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("price"), default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name=_("logo"))

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    class Meta:
        verbose_name = _('course')
        verbose_name_plural = _('courses')


class Lesson(BaseModel):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name=_('Course name'))
    num = models.PositiveIntegerField(verbose_name=_("lesson number"))

    title = models.CharField(max_length=256, verbose_name=_("name"))
    description = models.TextField(verbose_name=_("description"), blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name=_("As markdown"), default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        ordering = ("course", "num")
        verbose_name = _('lesson')
        verbose_name_plural = _('lessons')


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)

    name_first = models.CharField(max_length=128, verbose_name=_("first name"))
    name_second = models.CharField(max_length=128, verbose_name=_("last name"))

    day_birth = models.DateField(verbose_name=_("date birth"))
    deleted = models.BooleanField(default=False, verbose_name=_('Deleted'))

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _('teacher')
        verbose_name_plural = _('teachers')


class CourseFeedback(BaseModel):

    RATINGS = (
        (5, '⭐⭐⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (3, '⭐⭐⭐'),
        (2, '⭐⭐'),
        (1, '⭐'),
    )
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name=_('Course'))
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_('User'))
    rating = models.SmallIntegerField(choices=RATINGS, default=5, verbose_name=_('rating'))
    feedback = models.TextField(default=_('Without a review'), verbose_name=_('feedback'))

    class Meta:
        verbose_name = _('feedback')
        verbose_name_plural = _('feedbacks')

    def __str__(self):
        return f'Отзыв на {self.course} от {self.user}'

mainapp/forms.py
from django import forms

from mainapp.models import CourseFeedback


class CourseFeedBackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if course and user:
            self.fields['course'].initial = course.pk
            self.fields['user'].initial = user.pk

    class Meta:
        model = CourseFeedback
        fields = ('course', 'user', 'rating', 'feedback')
        widgets = {
            'course': forms.HiddenInput(),
            'user': forms.HiddenInput(),
        }

mainapp/views.py
from django.conf import settings
from django.core.cache import cache
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DetailView, DeleteView, View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, FileResponse, HttpResponseRedirect
from django.template.loader import render_to_string

import mainapp.forms
from mainapp import tasks
from mainapp.models import News, Courses, CourseFeedback
from mainapp import models as mainapp_models
from mainapp.forms import CourseFeedBackForm


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class NewsPageView(ListView):
    model = News
    template_name = "mainapp/news_list.html"
    paginate_by = 5
    ordering = '-id'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return super().get_queryset()
        return super().get_queryset().filter(deleted=False)


class NewsDetailView(DetailView):
    model = News


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.add_news',)


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.change_news',)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.delete_news',)


class LoginPageView(TemplateView):
    template_name = "authapp/login.html"


class CoursesListView(ListView):
    model = Courses
    paginate_by = 5
    ordering = ['-pk']


class CoursesDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context["course_object"] = get_object_or_404(mainapp_models.Courses, pk=pk)
        context["lessons"] = mainapp_models.Lesson.objects.filter(course=context["course_object"])
        context["teachers"] = mainapp_models.CourseTeachers.objects.filter(course=context["course_object"])

        if not self.request.user.is_anonymous:
            if not CourseFeedback.objects.filter(course=context["course_object"], user=self.request.user).count():
                context['feedback_form'] = mainapp.forms.CourseFeedBackForm(
                    course=context['course_object'],
                    user=self.request.user
                )
        feedback_list_key = f'course_feedback_{context["course_object"].pk}'
        cached_feedback_list = cache.get(feedback_list_key)

        if not cached_feedback_list:
            context["feedback_list"] = (
                CourseFeedback.objects.filter(course=context["course_object"])
                .order_by("-created", "-rating")[:5]
                .select_related()
            )
            cache.set(feedback_list_key, context["feedback_list"], timeout=300)

            # archive object for test -->
            import pickle
            with open(f'mainapp/fixtures/005_feedback_list_{pk}.bin', 'wb') as outf:
                pickle.dump(context["feedback_list"], outf)
            # <-- archive

        else:
            context["feedback_list"] = cached_feedback_list

        return context


class CourseFeedbackCreateView(CreateView):
    model = CourseFeedback
    form_class = CourseFeedBackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_template = render_to_string('mainapp/includes/feedback_card.html', context={'item': self.object})
        return JsonResponse({'card': rendered_template})


class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"

    def post(self, *args, **kwargs):
        # delay делает задачу отложенной (чтобы она попадала в общую очередь задач)
        message_from = self.request.POST.get('message_from')
        message_body = self.request.POST.get('message_body')
        tasks.send_feedback_to_email.delay(message_from, message_body)

        return HttpResponseRedirect(reverse_lazy('mainapp:contacts'))


class DocSitePageView(TemplateView):
    template_name = "mainapp/doc_site.html"


class LogView(UserPassesTestMixin, TemplateView):
    template_name = 'mainapp/logs.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        log_lines = []
        with open(settings.BASE_DIR / 'log/main_log.log') as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:
                    break
                log_lines.insert(0, line)

            context_data['logs'] = log_lines
        return context_data


class LogDownloadView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, 'rb'))

mainapp/templates/mainapp/includes/feedback_card.html
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ item.get_rating_display }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
        <p class="card-text">
            {{ item.feedback }}
        </p>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_mainapp_menu.html
{% load static i18n %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:main_page' %}">
            <img src="{% static 'img/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li
                        class="nav-item {% if request.resolver_match.view_name == 'mainapp:news' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:news' %}">{% translate 'News' %}</a>
                </li>
                <li
                        class="nav-item {% if request.resolver_match.view_name == 'mainapp:courses' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:courses' %}">{% translate 'Courses' %}</a>
                </li>
                <li
                        class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:contacts' %}">{% translate 'Contacts' %}</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="ddProfile"
                           role="button" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">
                            {% translate 'Your profile' %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="ddProfile">
                            <a class="dropdown-item" href="{% url 'authapp:edit' user.pk %}">{% translate 'Edit profile' %}</a>
                            <a class="dropdown-item" href="#">{% translate 'My courses' %}</a>
                            <div class="dropdown-divider"></div>
                            {% if user.is_staff %}
                                <a class="dropdown-item" href="{% url 'admin:index' %}">{% translate 'Moderation' %}</a>
                            {% endif %}
                            {% if user.is_superuser %}
                                <a class="dropdown-item" href="{% url 'admin:index' %}">{% translate 'Administration' %}</a>
                                <a class="dropdown-item" href="{% url 'mainapp:log_list' %}">{% translate 'Logs' %}</a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'authapp:logout' %}">{% translate 'Logout' %}</a>
                        </div>
                    </li>
                {% else %}
                    <a class="nav-link"
                       href="">{{ user.first_name|default:user.username }}</a>
                    <li><a class="nav-link" href="{% url 'authapp:login' %}">{% translate 'Login' %}</a>
                    </li>
                {% endif %}

            </ul>

        <div class="row">
            <div class="col p-0 border-right">
                <form action="{% url 'set_language' %}" method="POST">
                    {% csrf_token %}
                    <input name="language" value="ru" type="hidden">
                    <button class="btn btn-light" type="submit">🇷🇺</button>
                </form>
            </div>
            <div class="col p-0 border-left">
                <form action="{% url 'set_language' %}" method="POST">
                    {% csrf_token %}
                    <input name="language" value="en" type="hidden">
                    <button class="btn btn-light" type="submit">🇬🇧   </button>
                </form>
            </div>
        </div>
        </div>
    </div>
</nav>

mainapp/templates/mainapp/includes/inc_paginator.html
<div class="row justify-content-center align-items-center mt-3 mb-n3">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item "><a class="page-link"
                                          href="?page=1">Первая</a></li>
                <li class="page-item"><a class="page-link"
                                         href="?page={{ page_obj.previous_page_number }}"><</a></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                <li class="page-item {% if i == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ page_obj.next_page_number }}">></a></li>
                <li class="page-item"><a class="page-link"
                                         href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                </li>
            {% endif %}
        </ul>

    </nav>
</div>