Braniac/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include('django.conf.urls.i18n')),
    path("", include("mainapp.urls", namespace='mainapp')),
    path("authapp/", include("authapp.urls", namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))  # Подключение debug toolbar'a
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавления MEDIA_URL'a

authapp/urls.py
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView
from authapp.apps import AuthappConfig
from django.urls import path

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/<int:pk>', EditView.as_view(), name='edit'),
]

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from mainapp.models import NULLABLE


class User(AbstractUser):
    # Остальное наследуется от AbstractUser

    email = models.EmailField(blank=True, verbose_name=_('Email'))
    age = models.PositiveSmallIntegerField(**NULLABLE, verbose_name=_('age'))
    avatar = models.ImageField(**NULLABLE, upload_to='users', verbose_name=_('avatar'))

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

authapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# from django import forms

# class StyleFormMixin: # || аналог crispy
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             if isinstance(field.widget, forms.widgets.CheckboxInput):
#                 field.widget.attrs['class'] = 'form-check-input'
#             elif isinstance(field.widget, forms.DateTimeInput):
#                 field.widget.attrs['class'] = 'form-control flatpickr-basic'
#             if isinstance(field.widget, forms.TimeInput):
#                 field.widget.attrs['class'] = 'form-control flatpickr-time'
#             if isinstance(field.widget, forms.widgets.SelectMultiple):
#                 field.widget.attrs['class'] = 'select2 form-control select2-multiple'
#             else:
#                 field.widget.attrs['class'] = 'form-control'


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError(_("You're too young"))
        return age


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError(_("You're too young"))
        return age

authapp/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.utils.translation import gettext_lazy as _
from authapp.forms import CustomUserCreationForm, CustomUserChangeForm
from authapp.models import User
from django.contrib.auth.views import LoginView, LogoutView


class CustomLoginView(LoginView):
    template_name = 'authapp/login.html'
    extra_context = {
        'title': _('Authorization')
    }


class RegisterView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('mainapp:main_page')


class CustomLogoutView(LogoutView):
    pass


class EditView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'authapp/edit.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('authapp:edit', args=[self.request.user.pk])

authapp/templates/authapp/base.html
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">
    <link rel="icon" type="image/x-icon" href={% static "/favicon.ico" %}>


    <title>{% translate 'Welcome to Braniac!' %}</title>
</head>
<body>

{% include 'authapp/includes/inc_messages.html' %}

<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
    <div class="text-center">
        <p>
            <a href="/"><img src="{% static '/img/logo.png' %}" alt=""></a>
        </p>
        <h2>{{ title }}</h2>
        {% block content %}
        {% endblock %}
        <h4>{% translate 'Auth from social network' %}</h4>
        <p>
        <div class="btn-group btn-block" role="group">
            <a class="btn btn-primary"
               href="{% url 'social:begin' 'vk-oauth2' %}" role="button"><i class="fab fa-vk"></i></a>
            <a class="btn btn-primary" href="{% url 'social:begin' 'github' %}" role="button"><i
                    class="fab fa-github"></i></a>
            <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
        </div>
        </p>
    </div>
</div>


<!-- JavaScript section -->
<!-- Bootstrap -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- ChartJs -->
<script src="{% static 'js/Chart.min.js' %}"></script>

<!-- FontAwesome -->
<script src="{% static 'js/fontawesome.all.min.js' %}"></script>
{% block js %}

{% endblock %}

</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags i18n %}
{% block content %}
    <form class="col-6 m-auto pt-5 pb-5" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <p>
            <button type="submit" class="btn btn-primary btn-block">
                {% translate 'save' %}
            </button>
        </p>
    </form>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load i18n %}

{% block content %}
    {% if form.errors %}
        <p>{% translate 'Incorrect login or password' %}</p>
    {% endif %}
    {% if next %}
        {% if user.is_authenticated %}
            <p>{% translate "Your account doesn't have access to this page. To proceed, please login with an account that has access." %}</p>
        {% else %}
            <p>{%  translate "Please login to see this page." %}</p>
        {% endif %}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <p>
            <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username"
                   maxlength="150" class="textinput textInput form-control" required="" id="id_username"
                   placeholder="Username">
        </p>
        <p>
            <input type="password" name="password" autocomplete="current-password"
                   class="textinput textInput form-control" required="" id="id_password" placeholder="Password">
        </p>
        <p>
            <button type="submit" class="btn btn-primary btn-block">{% translate 'login' %}</button>
        </p>
    </form>
    <p>
    <div class="row justify-content-between">
        <div class="col">
            <a href="{% url 'authapp:register' %}"><small>{% translate "Sign up" %}</small></a>
        </div>
        <div class="col">
            <a href="#"><small>{% translate 'Forgot password?' %}</small></a>
        </div>
    </div>
    </p>
{% endblock %}

authapp/templates/authapp/user_form.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags i18n %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit"
                    class="btn btn-primary btn-block">
                {% translate 'Sign up' %}
            </button>
        </p>
    </form>
    <p>
    <div class="row justify-content-between">
        <div class="col">
            <a href="{% url 'authapp:login' %}"><small>{% translate 'login' %}</small></a>
        </div>
        <div class="col">
            <a href="#"><small>{% translate 'forgot password?' %}</small></a>
        </div>
    </div>
    </p>


{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}