Braniac/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include('django.conf.urls.i18n')),
    path("", include("mainapp.urls", namespace='mainapp')),
    path("authapp/", include("authapp.urls", namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))  # Подключение debug toolbar'a
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавления MEDIA_URL'a

authapp/urls.py
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView
from authapp.apps import AuthappConfig
from django.urls import path

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/<int:pk>', EditView.as_view(), name='edit'),
]

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("login/", views.LoginPageView.as_view(), name="login"),

    # Courses
    path("courses/", cache_page(300)(views.CoursesListView.as_view()), name="courses"),
    path("courses/<int:pk>/", views.CoursesDetailView.as_view(), name="courses_detail", ),
    path("courses/feedback/", views.CourseFeedbackCreateView.as_view(), name="course_feedback", ),

    # News
    path("news/", views.NewsPageView.as_view(), name="news"),
    path("news/add/", views.NewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/update/", views.NewsUpdateView.as_view(), name="news_update"),
    path("news/<int:pk>/delete/", views.NewsDeleteView.as_view(), name="news_delete"),
    path("news/<int:pk>/detail/", views.NewsDetailView.as_view(), name="news_detail"),

    # Logs
    path("logs/", views.LogView.as_view(), name="log_list"),
    path("logs/download/", views.LogDownloadView.as_view(), name="log_download"),

]

mainapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

NULLABLE = {'blank': True, 'null': True}


class MyCustomManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class BaseModel(models.Model):
    # objects = MyCustomManager()
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("created"), editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name=_("updated"), editable=False)

    deleted = models.BooleanField(default=False, verbose_name=_('deleted'))

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        abstract = True


class News(BaseModel):
    title = models.CharField(max_length=128, verbose_name=_('header'))
    preambule = models.CharField(max_length=1024, verbose_name=_('short description'))

    body = models.TextField(**NULLABLE, verbose_name=_('body'))
    body_as_markdown = models.BooleanField(
        default=False, verbose_name=_('As markdown')
    )

    def __str__(self):
        return f'{self.pk} {self.title}'

    class Meta:
        verbose_name = _('News')
        verbose_name_plural = _('News')


class Courses(BaseModel):
    name = models.CharField(max_length=256, verbose_name=_("name"))

    description = models.TextField(verbose_name=_("Description"), blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name=_("As markdown"), default=False)

    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("price"), default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name=_("logo"))

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    class Meta:
        verbose_name = _('course')
        verbose_name_plural = _('courses')


class Lesson(BaseModel):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name=_('Course name'))
    num = models.PositiveIntegerField(verbose_name=_("lesson number"))

    title = models.CharField(max_length=256, verbose_name=_("name"))
    description = models.TextField(verbose_name=_("description"), blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name=_("As markdown"), default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        ordering = ("course", "num")
        verbose_name = _('lesson')
        verbose_name_plural = _('lessons')


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)

    name_first = models.CharField(max_length=128, verbose_name=_("first name"))
    name_second = models.CharField(max_length=128, verbose_name=_("last name"))

    day_birth = models.DateField(verbose_name=_("date birth"))
    deleted = models.BooleanField(default=False, verbose_name=_('Deleted'))

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _('teacher')
        verbose_name_plural = _('teachers')


class CourseFeedback(BaseModel):

    RATINGS = (
        (5, '⭐⭐⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (3, '⭐⭐⭐'),
        (2, '⭐⭐'),
        (1, '⭐'),
    )
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name=_('Course'))
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_('User'))
    rating = models.SmallIntegerField(choices=RATINGS, default=5, verbose_name=_('rating'))
    feedback = models.TextField(default=_('Without a review'), verbose_name=_('feedback'))

    class Meta:
        verbose_name = _('feedback')
        verbose_name_plural = _('feedbacks')

    def __str__(self):
        return f'Отзыв на {self.course} от {self.user}'

mainapp/forms.py
from django import forms

from mainapp.models import CourseFeedback


class CourseFeedBackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if course and user:
            self.fields['course'].initial = course.pk
            self.fields['user'].initial = user.pk

    class Meta:
        model = CourseFeedback
        fields = ('course', 'user', 'rating', 'feedback')
        widgets = {
            'course': forms.HiddenInput(),
            'user': forms.HiddenInput(),
        }

mainapp/views.py
from django.conf import settings
from django.core.cache import cache
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DetailView, DeleteView, View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, FileResponse, HttpResponseRedirect
from django.template.loader import render_to_string

import mainapp.forms
from mainapp import tasks
from mainapp.models import News, Courses, CourseFeedback
from mainapp import models as mainapp_models
from mainapp.forms import CourseFeedBackForm


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class NewsPageView(ListView):
    model = News
    template_name = "mainapp/news_list.html"
    paginate_by = 5
    ordering = '-id'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return super().get_queryset()
        return super().get_queryset().filter(deleted=False)


class NewsDetailView(DetailView):
    model = News


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.add_news',)


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.change_news',)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.delete_news',)


class LoginPageView(TemplateView):
    template_name = "authapp/login.html"


class CoursesListView(ListView):
    model = Courses
    paginate_by = 5
    ordering = ['-pk']


class CoursesDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context["course_object"] = get_object_or_404(mainapp_models.Courses, pk=pk)
        context["lessons"] = mainapp_models.Lesson.objects.filter(course=context["course_object"])
        context["teachers"] = mainapp_models.CourseTeachers.objects.filter(course=context["course_object"])

        if not self.request.user.is_anonymous:
            if not CourseFeedback.objects.filter(course=context["course_object"], user=self.request.user).count():
                context['feedback_form'] = mainapp.forms.CourseFeedBackForm(
                    course=context['course_object'],
                    user=self.request.user
                )
        feedback_list_key = f'course_feedback_{context["course_object"].pk}'
        cached_feedback_list = cache.get(feedback_list_key)

        if not cached_feedback_list:
            context["feedback_list"] = (
                CourseFeedback.objects.filter(course=context["course_object"])
                .order_by("-created", "-rating")[:5]
                .select_related()
            )
            cache.set(feedback_list_key, context["feedback_list"], timeout=300)

            # archive object for test -->
            import pickle
            with open(f'mainapp/fixtures/005_feedback_list_{pk}.bin', 'wb') as outf:
                pickle.dump(context["feedback_list"], outf)
            # <-- archive

        else:
            context["feedback_list"] = cached_feedback_list

        return context


class CourseFeedbackCreateView(CreateView):
    model = CourseFeedback
    form_class = CourseFeedBackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_template = render_to_string('mainapp/includes/feedback_card.html', context={'item': self.object})
        return JsonResponse({'card': rendered_template})


class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"

    def post(self, *args, **kwargs):
        # delay делает задачу отложенной (чтобы она попадала в общую очередь задач)
        message_from = self.request.POST.get('message_from')
        message_body = self.request.POST.get('message_body')
        tasks.send_feedback_to_email.delay(message_from, message_body)

        return HttpResponseRedirect(reverse_lazy('mainapp:contacts'))


class DocSitePageView(TemplateView):
    template_name = "mainapp/doc_site.html"


class LogView(UserPassesTestMixin, TemplateView):
    template_name = 'mainapp/logs.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        log_lines = []
        with open(settings.BASE_DIR / 'log/main_log.log') as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:
                    break
                log_lines.insert(0, line)

            context_data['logs'] = log_lines
        return context_data


class LogDownloadView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, 'rb'))

mainapp/templates/mainapp/base.html
{% load static i18n %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <link rel="icon" type="image/x-icon" href={% static "/favicon.ico" %} >

    <title>
        {% block title %}
            {% translate 'Welcome to Braniac!' %}
        {% endblock title %}
    </title>
</head>

<body>

{% include 'mainapp/includes/inc_mainapp_menu.html' %}

<div class="container-md">

    {% block content %}
    {% endblock content %}

</div>

<!-- Footer -->

<div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Braniac</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="{% url 'mainapp:main_page' %}">{% translate 'Home page' %}</a></li>
                <li><a href="{% url 'mainapp:news' %}">{% translate 'News' %}</a></li>
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'authapp:login' %}">{% translate 'Login' %}</a></li>
                {% else %}
                    <li><a href="{% url 'authapp:logout' %}">{% translate 'Logout' %}</a></li>
                {% endif %}
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>{% translate 'About' %}</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="#">{% translate 'Terms & Conditions' %}</a></li>
                <li><a href="#">{% translate 'Privacy & Cookies' %}</a></li>
                <li><a href="#">{% translate 'API Documentation' %}</a></li>
                <li><a href="{% url 'mainapp:doc_site' %}">{% translate 'Site documentation' %}</a>
                </li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>{% translate 'Our social: ' %}</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a>
                </div>
                <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a>
                </div>
                <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
            </div>
            </p>
            <p>
                <strong>{% translate 'Our apps:' %}</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a>
                </div>
                <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-windows fa-2x"></i></a>
                </div>
            </div>
            </p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div>
            <p><small>&copy; mysite {% now 'Y' %}</small></p>
        </div>
    </div>
</div>

<!-- /Footer -->


<!-- JavaScript section -->
<!-- Bootstrap -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- ChartJs -->
<script src="{% static 'js/Chart.min.js' %}"></script>

<!-- FontAwesome -->
<script src="{% static 'js/fontawesome.all.min.js' %}"></script>
{% block js %}
{% endblock %}


</body>

</html>

mainapp/templates/mainapp/courses_detail.html
{% extends 'mainapp/base.html' %}
{% load static markdownify crispy_forms_tags cache i18n %}

{% block title %}
    {{ course_object.name }}
{% endblock title %}

{% block content %}
    <h1 class="mt-2">
        {{ course_object.name }}
    </h1>
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-6 col-lg-8 order-2 order-md-1">
            <div class="row h-100">
                <div class="col-12">
                    {% if course_object.description_as_markdown %}
                        {{ course_object.description|markdownify }}
                    {% else %}
                        {{ course_object.description }}
                    {% endif %}
                </div>
                <div class="col-12 align-self-end">
                    <p>
                        <small>{% translate 'Teachers' %}</small><br>
                        {% for item in teachers %}
                            {{ item.name_second }} {{ item.name_first }}{% if forloop.last %}{% else %},{% endif %}
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 order-1 order-md-2">
            <div class="row h-100">
                <div class="col-12 align-self-start">
                    <img class="w-100" src="{% static course_object.cover %}">
                </div>
                <div class="col-12 align-self-end d-none d-md-block">
                    <p class="text-center mt-2">
                        <small class="text-uppercase">{% translate 'Price' %}</small><br>
                        <span style="font-size: 30pt;">{{ course_object.cost }}</span>
                        <br>
                        <a href="#" class="btn btn-outline-primary btn-block"
                           role="button">{% translate 'Buy' %}</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 d-md-none order-3 order-sm-3">
            <p class="text-center">
                <small class="text-uppercase">{% translate 'Price' %}</small><br>
                <span style="font-size: 30pt;">
        {{ course_object.cost }}
      </span><br>
                <a href="#" class="btn btn-outline-primary btn-block"
                   role="button">{% translate 'Buy' %}</a>
            </p>
        </div>
    </div>
    <div class="accordion" id="accordionLessons">

        {% cache 300 lessons %}
            {% for item in lessons %}
                <div class="card">
                    <div class="card-header" id="headLessonPk{{ item.pk }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button"
                                    data-toggle="collapse" data-target="#collapse{{ item.pk }}"
                                    aria-expanded="true" aria-controls="collapse{{ item.pk }}">
                                {{ item.course.name }} - {{ item.title }}
                            </button>
                        </h2>
                    </div>

                    <div id="collapse{{ item.pk }}" class="collapse"
                         aria-labelledby="headLessonPk{{ item.pk }}"
                         data-parent="#accordionLessons">
                        <div class="card-body">
                            <div class="row justify-content-center">
                                <div class="col-12 text-center">
                                    <img src="{% static 'img/no_image.svg' %}" width="250px">
                                </div>
                                <div class="col-12">
                                    {% if item.description_as_markdown %}
                                        {{ item.description|markdownify }}
                                    {% else %}
                                        {{ item.description }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endcache %}

    </div>
    <h3>{% translate 'Feedbacks' %}</h3>

    <div id="feedback_list">
        {% if feedback_list %}
            {% for item in feedback_list %}
                {% include 'mainapp/includes/feedback_card.html' %}
            {% endfor %}
        {% else %}
            <p id="feedbackBeFirst">
                {% translate 'No feedback yet. Be first!' %}
            </p>
        {% endif %}
    </div>

    {% if feedback_form %}
        <div class="card" id="cardForm">
            <div class="card-body">
                <h5 class="card-title">{% translate 'Add feedback' %}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{% translate "You haven't left a review for this yet course" %}</h6>
                <p class="card-text">
                <form action="{% url 'mainapp:course_feedback' %}" method="POST"
                      id="feedbackForm">
                    {% csrf_token %}
                    {{ feedback_form|crispy }}
                </form>
                <button id="feedbackSubmit"
                        class="btn btn-primary btn-block">{% translate 'Send' %}
                </button>
                </p>
            </div>
        </div>
    {% endif %}

{% endblock content %}

{% block js %}
    <script>
        $(document).ready(function () {

            {% if feedback_form %}
                $("#feedbackSubmit").click(function () {

                    $("#cardForm").hide();
                    $("#feedbackBeFirst").hide();

                    var $form = $("#feedbackForm");
                    $.ajax({
                        type: "POST",
                        url: $form.attr("action"),
                        data: $form.serialize(),
                        success: function (data) {
                            $("#feedback_list").append(data.card);
                        }
                    });

                });
            {% endif %}

        });
    </script>
{% endblock js %}

mainapp/templates/mainapp/courses_list.html
{% extends 'mainapp/base.html' %}
{% load static i18n %}

{% block title %}
    {% translate 'Courses' %}
{% endblock title %}

{% block content %}

    <div class="row justify-content-center mt-3">


        {% for item in object_list %}
            <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="{% url 'mainapp:courses_detail' pk=item.pk %}">
                    <img src="{% static item.cover %}" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ item.name }}</h5>
                    </div>
                </a>
            </div>
        {% endfor %}

    </div>
    {% include 'mainapp/includes/inc_paginator.html' %}


{% endblock content %}

mainapp/templates/mainapp/doc_site.html
{% extends 'mainapp/base.html' %}
{% load i18n %}
{% block content %}
    <div class="container-md">
        <div class="row justify-content-center align-items-center mt-3">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        {% translate 'Site documentation' %}
                    </div>
                    <div class="card-body">

                        <h5 class="card-title">{% translate 'CSS' %}</h5>
                        <p class="card-text">
                        <ul>
                            <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/"
                                   target="_blank">Bootstrap
                                v4.6</a></li>
                            <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
                        </ul>
                        </p>

                        <h5 class="card-title">{% translate 'Icons' %}</h5>
                        <p class="card-text">
                            <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome
                                5.15.3</a>
                        </p>

                        <h5 class="card-title">{% translate 'Сharts' %}</h5>
                        <p class="card-text">
                            <a href="https://www.chartjs.org/">ChartJS</a>
                        </p>

                        <h5 class="card-title">{% translate 'Graphics' %}</h5>
                        <p class="card-text">
                        <ul>
                            <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">{% translate 'Logo' %}
                                by
                                flamingtext.com</a></li>
                            <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">{% translate 'Photo' %}
                                by
                                pexels.com</a>.
                                {% translate 'All images are distributed under a free license. For the reviews page, the photos must have an aspect ratio multiple of 2.912 (for example, 1920x659)' %}
                            </li>
                        </ul>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/logs.html
{% extends 'mainapp/base.html' %}
{% load i18n %}
{% block content %}
    <div class="card">
        <div class="card-header">{% translate 'First 1000 logs' %}
            <a href="{% url 'mainapp:log_download' %}" class="btn btn-outline-warning ">{% translate 'Download logs' %}</a>
        </div>
        <div class="card-body">
            {% for line in logs %}
                {{ line }} <br>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/news_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load i18n %}
{% block content %}
    <div class="row justify-content-center pt-3">
        <div class="col-md-8 col-lg-6">
            <h2>{% translate 'Mark as deleted?' %}</h2>
            <p>
                {% translate 'Make a note to delete the news' %}:<br>
                "{{ object.title }}" {% translate 'from' %} {{ object.created }}
            </p>
            <p>
            <div class="row">
                <div class="col-6">
                    <form action="{% url 'mainapp:news_delete' pk=object.pk %}"
                          method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-block"
                                type="submit">{% translate 'Accept' %}
                        </button>
                    </form>
                </div>
                <div class="col-6">
                    <a class="btn btn-primary btn-block" href="{% url 'mainapp:news' %}"
                       role="button">{% translate 'Decline' %}]</a>
                </div>
            </div>
            </p>
        </div>
    </div>
{% endblock content %}

mainapp/templates/mainapp/news_form.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags i18n%}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-12 col-lg-8">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit"
        class="btn btn-primary btn-block">{% translate 'Post' %}</button>
    </form>
  </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/news_list.html
{% extends 'mainapp/base.html' %}
{% load i18n %}

{% block title %}
    Новости
{% endblock title %}
{% block content %}
    {% if page_num %}
        <div class="card my-2">
            <div class="card-body">
                <p class="card-text">{% translate 'Current page' %}: {{ page_num }}</p>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-lg-8">
            {% for item in page_obj %}
                <div class="card my-2">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            {{ item.created|date:"Y-m-d h-i-s" }}
                        </h6>
                        <p class="card-text">{{ item.preambule }}</p>
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'mainapp:news_detail' pk=item.pk %}"
                                   class="card-link">{% translate 'more detailed' %}</a>
                            </div>
                            {% if perms.mainapp.change_news %}
                                <div class="col-1 text-center">
                                    <a href="{% url 'mainapp:news_update' pk=item.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>
                                </div>
                            {% endif %}
                            {% if perms.mainapp.delete_news %}
                                <div class="col-1 text-center">
                                    <a href="{% url 'mainapp:news_delete' pk=item.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-lg-4">
            <div class="card my-2 sticky-top">
                <div class="card-header">
                    {% translate 'Filters:' %}
                </div>
                <div class="card-body">
                    <form action="">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">{% translate 'Date from .. ' %}</span>
                            </div>
                            <input type="date" class="form-control" name="dateFrom">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">{% translate 'Date to ..' %}</span>
                            </div>
                            <input type="date" class="form-control" name="dateTo">
                        </div>
                        <button type="submit"
                                class="btn btn-primary btn-block">{% translate 'Filter' %}
                        </button>
                    </form>
                </div>
            </div>
            {% if perms.mainapp.add_news %}
                <a class="btn btn-primary btn-block" role="button"
                   href="{% url 'mainapp:news_create' %}">{% translate 'Add news' %}</a>
            {% endif %}
        </div>
    </div>

    {% include 'mainapp/includes/inc_paginator.html' %}

{% endblock content %}